//
// Created by louis on 11/23/19.
//

#ifndef SYSPRAKOTHELLO_BOARDTESTS_H
#define SYSPRAKOTHELLO_BOARDTESTS_H

#define MOVE int
#define SIDE_TO_MOVE int
#define BOARD int*
#define MOVES int*

#define BLACK 2
#define WHITE 1

#define STARTING_WHITE_POSITION_1 27
#define STARTING_WHITE_POSITION_2 36
#define STARTING_BLACK_POSITION_1 28
#define STARTING_BLACK_POSITION_2 35

#define STARTING_PLAYER BLACK
#define SWITCH_PLAYER_CONSTANT 3
int basicTests();

#endif //SYSPRAKOTHELLO_BOARDTESTS_H
