//
// Created by louis on 11/14/19.
//

#ifndef SYSPRAKOTHELLO_PERFORMCONNECTION_H
#define SYSPRAKOTHELLO_PERFORMCONNECTION_H


int performConnection(int sock);

#endif //SYSPRAKOTHELLO_PERFORMCONNECTION_H
