//
// Created by louis on 12/9/19.
//

#ifndef SYSPRAKOTHELLO_TESTKIBASICSTRATEGY_H
#define SYSPRAKOTHELLO_TESTKIBASICSTRATEGY_H

int kiTestsBasicStrategy();

#endif //SYSPRAKOTHELLO_TESTKIBASICSTRATEGY_H
