name: testGithubScript

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: scriptFromLectureIsh
      run: 
        cd scripts/ && 
        sudo apt install valgrind && 
        ./testGithubScript.sh
